# Site settings
title: vdaubry.github.io
email: vdaubry@gmail.com
author: Vincent Daubry
description: "A blog about backend development, mobile development, and entrepreneurship"
baseurl: ""
url: "http://fullgc.github.io"
github_username:  FullGC
linkedin_username: dani-shemesh

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap