# Site settings
title: Dani Shemesh
email: dani.shemesh@hotmail.com
author: FullGC
description: "A blog about backend development, Scala development and devops"
baseurl: ""
url: "http://fullgc.github.io"
github_username: FullGC
linkedin_username: dani-shemesh

# Build settings
markdown: kramdown
highlighter:
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap

disqus: FullGC
